services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Пробрасываем папку data внутрь, чтобы БД и фото сохранялись на SD-карте
      - ./data:/app/data
    ports:
      - "8000:8000"
